const menuArray = [
  // coffee
  {
    kindOf: "coffee",
    name: "에스프레소",
    menuImage: "./images/menus/mock.jpg",
    price: "3.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "coffee",
    name: "아메리카노",
    menuImage: "./images/menus/coffee/ice_americano.jpg",
    price: "3.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "coffee",
    name: "카페라떼",
    menuImage: "./images/menus/mock.jpg",
    price: "3.8",
    new: false,
    recommended: false,
  },
  {
    kindOf: "coffee",
    name: "카푸치노",
    menuImage: "./images/menus/mock.jpg",
    price: "3.8",
    new: false,
    recommended: false,
  },
  {
    kindOf: "coffee",
    name: "아포가토",
    menuImage: "./images/menus/mock.jpg",
    price: "4.8",
    new: false,
    recommended: false,
  },
  {
    kindOf: "coffee",
    name: "코코넛 커피",
    menuImage: "./images/menus/mock.jpg",
    price: "5.0",
    new: false,
    recommended: false,
  },
  {
    kindOf: "coffee",
    name: "꿀 아메리카노",
    menuImage: "./images/menus/mock.jpg",
    price: "4.0",
    new: false,
    recommended: false,
  },
  {
    kindOf: "coffee",
    name: "돌체 라떼",
    menuImage: "./images/menus/mock.jpg",
    price: "4.0",
    new: false,
    recommended: false,
  },
  {
    kindOf: "coffee",
    name: "아이스크림 라떼",
    menuImage: "./images/menus/mock.jpg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "coffee",
    name: "카라멜 마끼야또",
    menuImage: "./images/menus/mock.jpg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "coffee",
    name: "헤이즐럿 라떼",
    menuImage: "./images/menus/mock.jpg",
    price: "4.0",
    new: false,
    recommended: false,
  },
  // latte
  {
    kindOf: "latte",
    name: "녹차 라떼",
    menuImage: "./images/menus/mock.jpg",
    price: "4.0",
    new: false,
    recommended: false,
  },
  {
    kindOf: "latte",
    name: "녹차 초코 라떼",
    menuImage: "./images/menus/mock.jpg",
    price: "4.0",
    new: false,
    recommended: false,
  },
  {
    kindOf: "latte",
    name: "딸기 달콤 라떼",
    menuImage: "./images/menus/mock.jpg",
    price: "4.0",
    new: false,
    recommended: false,
  },
  {
    kindOf: "latte",
    name: "망고 달콤 라떼",
    menuImage: "./images/menus/mock.jpg",
    price: "4.0",
    new: false,
    recommended: false,
  },
  {
    kindOf: "latte",
    name: "미숫가루 라떼 (18가지 곡물)",
    menuImage: "./images/menus/mock.jpg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "latte",
    name: "민트초코 라떼",
    menuImage: "./images/menus/mock.jpg",
    price: "4.0",
    new: false,
    recommended: false,
  },
  {
    kindOf: "latte",
    name: "바닐라 라떼",
    menuImage: "./images/menus/mock.jpg",
    price: "4.0",
    new: false,
    recommended: false,
  },
  {
    kindOf: "latte",
    name: "바닐라빈 라떼",
    menuImage: "./images/menus/mock.jpg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "latte",
    name: "바닐라빈 라떼",
    menuImage: "./images/menus/mock.jpg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "latte",
    name: "밤/고구마 라떼",
    menuImage: "./images/menus/mock.jpg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "latte",
    name: "초코 라떼",
    menuImage: "./images/menus/mock.jpg",
    price: "4.0",
    new: false,
    recommended: false,
  },
  {
    kindOf: "latte",
    name: "토피넛 라떼",
    menuImage: "./images/menus/mock.jpg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  // dutch
  {
    kindOf: "dutch",
    name: "더치 커피",
    menuImage: "./images/menus/mock.jpg",
    price: "4.0",
    new: false,
    recommended: false,
  },
  {
    kindOf: "dutch",
    name: "더치 카페라떼",
    menuImage: "./images/menus/mock.jpg",
    price: "4.3",
    new: false,
    recommended: false,
  },
  {
    kindOf: "dutch",
    name: "더치 카푸치노",
    menuImage: "./images/menus/mock.jpg",
    price: "4.3",
    new: false,
    recommended: false,
  },
  {
    kindOf: "dutch",
    name: "더치 바닐라 라떼",
    menuImage: "./images/menus/mock.jpg",
    price: "4.3",
    new: false,
    recommended: false,
  },
  {
    kindOf: "dutch",
    name: "더치 헤이즐럿",
    menuImage: "./images/menus/mock.jpg",
    price: "4.3",
    new: false,
    recommended: false,
  },
  {
    kindOf: "dutch",
    name: "카라멜 마끼야또",
    menuImage: "./images/menus/mock.jpg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "dutch",
    name: "더치 아포카토",
    menuImage: "./images/menus/mock.jpg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "dutch",
    name: "더치 코코넛",
    menuImage: "./images/menus/mock.jpg",
    price: "4.8",
    new: false,
    recommended: false,
  },
  {
    kindOf: "dutch",
    name: "더치 카페모카",
    menuImage: "./images/menus/mock.jpg",
    price: "5.0",
    new: false,
    recommended: false,
  },
  {
    kindOf: "dutch",
    name: "바닐라빈 라떼",
    menuImage: "./images/menus/mock.jpg",
    price: "5.0",
    new: false,
    recommended: false,
  },
  {
    kindOf: "dutch",
    name: "아이스크림 라떼",
    menuImage: "./images/menus/mock.jpg",
    price: "5.0",
    new: false,
    recommended: false,
  },
  // smoothie
  {
    kindOf: "smoothie",
    name: "딸기 스무디",
    menuImage: "./images/menus/mock.jpg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "smoothie",
    name: "망고 스무디",
    menuImage: "./images/menus/mock.jpg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "smoothie",
    name: "키위 스무디",
    menuImage: "./images/menus/mock.jpg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "smoothie",
    name: "복숭아 스무디",
    menuImage: "./images/menus/smoothie/peach_smoothie.jpeg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "smoothie",
    name: "플레인요거트 스무디",
    menuImage: "./images/menus/mock.jpg",
    price: "5.0",
    new: false,
    recommended: false,
  },
  {
    kindOf: "smoothie",
    name: "딸기 요거트 스무디",
    menuImage: "./images/menus/smoothie/strawberry_smoothie.jpeg",
    price: "5.0",
    new: false,
    recommended: false,
  },
  {
    kindOf: "smoothie",
    name: "블루베리 요거트",
    menuImage: "./images/menus/mock.jpg",
    price: "5.0",
    new: false,
    recommended: false,
  },
  {
    kindOf: "smoothie",
    name: "딸기 밀크 쉐이크",
    menuImage: "./images/menus/mock.jpg",
    price: "5.3",
    new: false,
    recommended: false,
  },
  {
    kindOf: "smoothie",
    name: "밀크 쉐이크",
    menuImage: "./images/menus/mock.jpg",
    price: "5.3",
    new: false,
    recommended: false,
  },
  // ade
  {
    kindOf: "ade",
    name: "레몬 (수제청)",
    menuImage: "./images/menus/mock.jpg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "ade",
    name: "블루레몬 (수제청)",
    menuImage: "./images/menus/mock.jpg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "ade",
    name: "자몽 (수제청)",
    menuImage: "./images/menus/mock.jpg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "ade",
    name: "청포도",
    menuImage: "./images/menus/mock.jpg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "ade",
    name: "깔라만시",
    menuImage: "./images/menus/mock.jpg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "ade",
    name: "패션후루츠 (수제청)",
    menuImage: "./images/menus/mock.jpg",
    price: "5.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "ade",
    name: "복숭아/ 망고",
    menuImage: "./images/menus/mock.jpg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "ade",
    name: "수제 매실 에이드",
    menuImage: "./images/menus/mock.jpg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "ade",
    name: "청귤 에이드",
    menuImage: "./images/menus/mock.jpg",
    price: "4.5",
    new: false,
    recommended: false,
  },
  // fruitJuice
  {
    kindOf: "fruitJuice",
    name: "딸기 쥬스",
    menuImage: "./images/menus/mock.jpg",
    price: "5.3",
    new: false,
    recommended: false,
  },
  {
    kindOf: "fruitJuice",
    name: "망고 쥬스",
    menuImage: "./images/menus/mock.jpg",
    price: "5.3",
    new: false,
    recommended: false,
  },
  {
    kindOf: "fruitJuice",
    name: "키위 쥬스",
    menuImage: "./images/menus/mock.jpg",
    price: "5.3",
    new: false,
    recommended: false,
  },
  {
    kindOf: "fruitJuice",
    name: "수박(시즌) 쥬스",
    menuImage: "./images/menus/mock.jpg",
    price: "5.8",
    new: false,
    recommended: false,
  },
  {
    kindOf: "fruitJuice",
    name: "토마토 쥬스",
    menuImage: "./images/menus/mock.jpg",
    price: "5.8",
    new: false,
    recommended: false,
  },
  {
    kindOf: "fruitJuice",
    name: "한라봉 쥬스",
    menuImage: "./images/menus/mock.jpg",
    price: "5.8",
    new: false,
    recommended: false,
  },
  // tea
  {
    kindOf: "tea",
    name: "얼그레이 (홍차)",
    menuImage: "./images/menus/mock.jpg",
    price: "3.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "tea",
    name: "캐모마일",
    menuImage: "./images/menus/mock.jpg",
    price: "3.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "tea",
    name: "페퍼민트",
    menuImage: "./images/menus/mock.jpg",
    price: "3.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "tea",
    name: "히비스커스",
    menuImage: "./images/menus/mock.jpg",
    price: "3.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "tea",
    name: "루이보스",
    menuImage: "./images/menus/mock.jpg",
    price: "3.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "tea",
    name: "녹차",
    menuImage: "./images/menus/mock.jpg",
    price: "3.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "tea",
    name: "레몬 (수제청)",
    menuImage: "./images/menus/mock.jpg",
    price: "4.0",
    new: false,
    recommended: false,
  },
  {
    kindOf: "tea",
    name: "유자/ 생강/ 자몽",
    menuImage: "./images/menus/mock.jpg",
    price: "4.0",
    new: false,
    recommended: false,
  },
  {
    kindOf: "tea",
    name: "매실",
    menuImage: "./images/menus/mock.jpg",
    price: "4.0",
    new: false,
    recommended: false,
  },
  {
    kindOf: "tea",
    name: "밀크티",
    menuImage: "./images/menus/mock.jpg",
    price: "4.0",
    new: false,
    recommended: false,
  },
  {
    kindOf: "tea",
    name: "복숭아 아이스티",
    menuImage: "./images/menus/mock.jpg",
    price: "3.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "tea",
    name: "레몬 아이스티",
    menuImage: "./images/menus/mock.jpg",
    price: "3.5",
    new: false,
    recommended: false,
  },
  {
    kindOf: "tea",
    name: "체리 아이스티",
    menuImage: "./images/menus/mock.jpg",
    price: "3.5",
    new: false,
    recommended: false,
  },
];
